### ISSUE TITLE
ffmpeg 0.10.2 build broken on gcc 4.8

### ISSUE THREAD

**Issue by soakbot** [waddlesplash/haikuports#98]
(Original issue 98 created by anevilyak on 2014-04-13T16:01:09.807024+00:00)

Attempting to build ffmpeg 0.10.2 since the update to gcc 4.8 now results in:

    libavcodec/h264_cabac.c: In function 'decode_cabac_mb_mvd':
    libavcodec/x86/cabac.h:109:5: error: 'asm' operand has impossible constraints
     __asm__ volatile(
  

It's possible 0.11 fixes this, but its recipe is currently broken.

**Comment by soakbot** [comment]
(Original issue 98 last updated on 2014-07-29T15:22:25.175348+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)

**Comment by soakbot** [comment]
(Original comment by waddlesplash on 2014-04-14T01:42:42.533275+00:00)

It appears that we can build 2.2.1 (the latest) on GCC4 quite easily. However, it does not build on GCC2, and will probably not without many fixes.

Perhaps 0.11.whatever should remain the last GCC2 version and GCC4 will get the latest?

**Comment by soakbot** [comment]
(Original comment by pulkomandy on 2014-04-19T21:39:08.454253+00:00)

0.11 doesn't fix that issue.

We can run different versions of ffmpeg for gcc2 and 4 (updated recipe for gcc4 latest version welcome!), but the ffmpeg media add-on may need some tweaks to compile with both versions of ffmpeg (with some #ifdef around relevant part of the code). This is the only issue I can think of.

**Comment by soakbot** [comment]
(Original comment by waddlesplash on 2014-04-20T03:40:33.201580+00:00)

OK, I'll work on converting the 0.11 bep into a recipe for GCC2, and I'll write a recipe for 2.2.1. @pulkomandy would you be willing to update the media kit once I do that? I have no skill in that area...

**Comment by soakbot** [comment]
(Original comment by waddlesplash on 2014-07-28T16:39:23.243692+00:00)

It appears that 0.11 was causing problems on GCC2. It's possible these were solved by stack alignment, but I am not going to work on that for now.

I'm instead looking at 0.10.14, which is a much newer (June 2014) version of 0.10 that seems to resolve a lot of these issues; however, this one is still present...

**Comment by soakbot** [comment]
(Original comment by waddlesplash on 2014-07-28T21:17:05.802078+00:00)

The build is still broken on GCC4 for 0.10, but there is now a working 2.3 recipe in the repo.

We cannot close this yet because Haiku still uses 0.10 on GCC4...

**Comment by soakbot** [comment]
(Original comment by waddlesplash on 2014-07-29T15:22:19.745839+00:00)

Fixed by 23fd6c807b935f70f2bd3dc01837dcfdc052903f!
